spring.application.name=news_management

# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/news-management-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# (???????????) ??????? ??????????? SQL-????????
spring.jpa.show-sql=true

# ???? ? changelog-????? (?????? ? src/main/resources)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.liquibase.default-schema=app
spring.liquibase.liquibase-schema=app

# ???????? liquibase ??? ?????? (?? ????????? true)
spring.liquibase.enabled=true

# ?????? Liquibase
# spring.liquibase.logging=INFO

# ???????? ?? ???? ????? ???????? ???????? (???? ?????????!)
# spring.liquibase.drop-first=true

# ???????? ? ????? ????????? ????? ???????? ????????? (???? ??????????? ?????????)
# spring.liquibase.contexts=dev,test,prod

# ????????? ??? ??????????? ? ???? (???? ?????????? ?? spring.datasource.*)
#spring.liquibase.url=jdbc:postgresql://localhost:5432/news-management-db
#spring.liquibase.user=postgres
#spring.liquibase.password=secret