spring.application.name=news_management

spring.datasource.url=jdbc:postgresql://localhost:5432/news-management-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.liquibase.default-schema=app
spring.liquibase.liquibase-schema=app

spring.liquibase.enabled=true
